sudo: required
language: node_js
services: 
    - docker

before_install:
    - docker build -t vijay01/dockeraws .

script:
    - docker exec -it vijay01/dockeraws npm run test 

deploy:
    region: us-west-2
    provider: elasticbeanstalk
    bucket-name: elasticbeanstalk-us-west-2-277569349877
    bucket-path: DockerAws
    app: DockerAws
    env: Dockeraws-env-1
    on:
        branch: master
    secret-access-key: $AWS_SECREAT_KEY
    access_key_id: $AWS_ACCESS_KEY

