sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t vijay01/dockeraws .

    script:
    - docker run -e CI=true vijay01/dockeraws

deploy:
    region: us-west-2
    provider: elasticbeanstalk
    bucket-name: elasticbeanstalk-us-west-2-277569349877
    bucket-path: DockerAws
    app: DockerAws
    env: Dockeraws-env-1
    on:
        branch: master
    secret-access-key: $AWS_SECREAT_KEY
    access_key_id: $AWS_ACCESS_KEY

